function out_img = beamform(sig, sz, delays, channels)
    out_img = interpn(  ...
                        (1:sig.n_chan()), ...
                        (1:sig.n_samp()), ...
                        sig.signals, ...
                        channels, ...
                        (delays - sig.start_t)*sig.fs, ...
                        'linear', ...
                        0 ...
    );
    out_img = sum(out_img, 2);
    out_img = reshape(out_img, sz);
end
